### ISSUE TITLE
Thread safety considerations

### ISSUE THREAD

**Issue by sonOfRa** [domcleal/rkerberos#10]
I'm using rkerberos in a rails app that is our password management frontend. What are the (if any) thread safety guarantees of the kadmin and krb5 classes?

Intuitively, I'm thinking that in case of the kadmin class it's safe to spawn multiple kadmin instances at the same time, but what about krb5? When two users change their password at roughly the same time, what happens in the following case: https://gist.github.com/sonOfRa/8460e65f7b42907328ef ?

**Comment by djberg96** [comment]
I would think the kerberos server would handle it fine, and shouldn't be difficult to test if you have a test user you can futz with.

See http://www.mail-archive.com/kerberos@mit.edu/msg17994.html for some discussion on thread safety. The rkerberos gem does nothing specifically in terms of thread safety.
