### ISSUE TITLE
Creating a new release

### ISSUE THREAD

**Issue by sonOfRa** [domcleal/rkerberos#20]
@domcleal @djberg96 Would one of you be willing to add me as an owner on https://rubygems.org/gems/rkerberos, so that I can create new releases at some point? I'm https://rubygems.org/profiles/sonOfRa on rubygems.

**Comment by djberg96** [comment]
@sonOfRa ok, I added you.

**Comment by sonOfRa** [comment]
Thank you.

**Comment by djberg96** [comment]
@sonOfRa You should add your email to the gemspec and add yourself to the "Authors" in the README.

**Comment by sonOfRa** [comment]
I'll do that in the commit that I'll tag for the next release, probably some time this weekend.
