### ISSUE TITLE
API inconsistencies

### ISSUE THREAD

**Issue by sonOfRa** [domcleal/rkerberos#21]
rkrb5_get_init_creds_keytab returns self on success, while rkrb5_get_init_creds_password returns true on success. Both throw exceptions on failure.

Should both be switched to the same behaviour, or should the old behaviour be retained for compatibility? My suggestion would be to have them both return self on success, as this allows chaining of calls. This would allow code that relied on the return value of rkrb5_get_init_creds_password being truthy to still function, and allow new code to chain calls.

**Comment by djberg96** [comment]
FWIW, I vote for `self`.
