### ISSUE TITLE
db_args in init functions

### ISSUE THREAD

**Issue by sonOfRa** [domcleal/rkerberos#8]
I'm currently invoking the kadmin shell utility to do some tasks against our kerberos which uses LDAP as a KDC Datastore. To create new principals, I need to specifiy the db_args (-x dn=... in the shell utility). Currently, this API doesn't support this (NULL is always passed as the db_args argument in the init functions).

Would you be interested in merging this functionality and cutting a new gem if I were to add it, or do you no longer support rkerberos?

**Comment by domcleal** [comment]
Yes, I'd be happy to.  I've not really been doing anything new with it lately, but still rely on it.

**Comment by sonOfRa** [comment]
The current calling convention for create principal has one argument for the username, and one for the password. In order to support db_args, I'd have to either add one parameter (v_db_args, an array of strings), or turn it into a hash (name: "foo", password: "bar", db_args: %w(containerdn=foo linkdn=bar). Which approach would you prefer?

**Comment by domcleal** [comment]
I'd suggest just adding a parameter, so as not to break compatibility.

**Comment by sonOfRa** [comment]
Something I noticed: You use StringValuePtr to acquire char* from ruby strings. This does not (necessarily) return a null-terminated string (StringValueCStr does). Does the kerberos API not expect null-terminated strings? I would find this surprising, since none of the functions that accept strings also expect a length parameter.

**Comment by djberg96** [comment]
@sonOfRa it's quite possible that needs to be refactored. :)
